spring:
  application:
    name: community-service

  jpa:
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080
  forward-headers-strategy: framework

file:
  upload-dir: ${FILE_UPLOAD_DIR:uploads}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}
